### ISSUE TITLE
Cannot get keyboard to show up on tithe amount

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/my.newspring.cc#101]
Replicate:
1. tap into tithe amount and put in a figure
2. close keyboard
3. open fund select
4. click tab backward - this brings up the normal iOS keyboard on tithe amount field
5. close iOS keyboard
6. tap on tithe amount - it no worky

@jbaxleyiii

**Comment by jbaxleyiii** [comment]
possible duplicate of #47
