### ISSUE TITLE
Mobile menu thing

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/my.newspring.cc#108]
Every once in a while the text "Menu" appears under the icon on mobile footer:

![photo aug 03 4 46 33 pm](https://cloud.githubusercontent.com/assets/816517/9047380/9c993da8-39ff-11e5-9352-02e4da790d33.png)

**Comment by jbaxleyiii** [comment]
@johnthepink the media query doesn't always run perfectly. We should force it to fire and also hide that with sass
