### ISSUE TITLE
Windows phone modals dont' lock the page

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/my.newspring.cc#114]
bwah

**Comment by johnthepink** [comment]
There seems to be a lot of issues with this type of thing. Possibly to do with the way Windows Phone calculates the viewport? Also, the various "fixes" mentioned around the internet claim to break desktop version of IE? Oh boy. May require some JS browser detection. Gross.

This may be easier to debug with a Windows Phone emulator, which seems to exist, but for Windows only.

Here are some things I found:

1. http://stackoverflow.com/questions/13996387/div-overflow-scrolling-when-ms-viewport-is-specified

2. http://mattstow.com/responsive-design-in-ie10-on-windows-phone-8.html

3. https://css-tricks.com/snippets/javascript/fix-ie-10-on-windows-phone-8-viewport/ 

4. http://timkadlec.com/2013/01/windows-phone-8-and-device-width/

**Comment by jbaxleyiii** [comment]
@johnthepink amazing investigation work, lets hold off on it

**Comment by johnthepink** [comment]
Oh also this may be of use:

https://github.com/twbs/bootstrap/issues/11153

**Comment by jbaxleyiii** [comment]
@johnthepink there is a new build of win10 for phones expected Friday. It should be stable enough for my daily driver and I can test edge with it

**Comment by jbaxleyiii** [comment]
@johnthepink Microsoft edge does not have this problem FWIW

**Comment by johnthepink** [comment]
@jbaxleyiii nice!
