### ISSUE TITLE
Gray out tithe if giving to other funds

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/my.newspring.cc#115]
To help the user know they aren't giving to tithe?

@samclaridge thoughts?

**Comment by samclaridge** [comment]
Not really sure how this would work. I imagine you'd have to have it be grayed out by default, unless you want to track if they click the select first and then modify the tithe sentence. 




The problem with graying out by default is it may not be readable at all, as we saw on the chrome books. If you can't see the placeholders it's not as bad as you still have an idea from the sentence of what you're supposed to do. However if the tithe sentence is grayed out by default too we could have people bailing cos they think the page hasn't loaded properly.

**Comment by jbaxleyiii** [comment]
@samclaridge agreed, it would be really tricky. Lets see how people react to the forms in a wide spread test before making any changes. It may be great. Closing for now.
