### ISSUE TITLE
Fix complete profile button location on give screen 

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#12]
When, profile isn't completed and a user returns to the home screen, the button is out of place.

https://www.dropbox.com/s/bzuzbyzz87rwr9t/Screenshot%202015-07-12%2009.00.00.png?dl=0

This works as expected on a fund detail page: https://www.dropbox.com/s/gp85c3ix6nrz130/Screenshot%202015-07-12%2009.04.15.png?dl=0

**Comment by jbaxleyiii** [comment]
This will be fixed with https://github.com/NewSpring/apollos-give/pull/35

**Comment by jonhorton** [comment]
dang that was fast. and already live!
