### ISSUE TITLE
Unable to remove additional fund

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#13]
After adding an additional fund to give to, it's impossible to remove it if a user changes their mind.

https://www.dropbox.com/s/nor2j764abnj40t/Screenshot%202015-07-12%2009.02.15.png?dl=0

I also tried clicking the menu button to go "home" but that didn't reset the page either.

**Comment by jbaxleyiii** [comment]
Will be fixed with https://github.com/NewSpring/apollos-give/pull/36
