### ISSUE TITLE
Can't move to step 2 of create account

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#15]
https://www.dropbox.com/s/6vosswwbitfic76/Screenshot%202015-07-12%2011.26.27.png?dl=0

Clicking the Next button does nothing, even with all fields complete.

**Comment by benwiley** [comment]
self._getFormComponent() of apollos.profile.information.coffee is returning null on alpha.  So far I cannot recreate this locally.

**Comment by benwiley** [comment]
I put a pull request in apollos-give
