### ISSUE TITLE
Additional fund inputs don't show the $

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#16]
When activating an additional fund, the $ sign doesn't initially appear in the input field
https://www.dropbox.com/s/v1aqvlpnqnj0kiw/Screenshot%202015-07-12%2016.07.00.png?dl=0

Seems inconsistent with the tithe input and potentially confusing to users.

**Comment by jbaxleyiii** [comment]
fixed with https://github.com/NewSpring/apollos-give/pull/38

**Comment by jonhorton** [comment]
Commenting in case it needs it.

This was also present on the fund detail page: 
https://www.dropbox.com/s/d0j52xd7mtkly4c/Screenshot%202015-07-12%2016.54.43.png?dl=0

**Comment by jbaxleyiii** [comment]
@jonhorton not sure if I grabbed that, going to repoen

**Comment by jbaxleyiii** [comment]
@jonhorton this was fixed with the last deploy: http://45.55.213.136/give/mission-fund
