### ISSUE TITLE
Mobile view has empty scrollbars fixed

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#17]
Not sure if this is because I'm viewing it on desktop, but there are 2 fixed scrollbars present:
https://www.dropbox.com/s/dwh55u8qoksn03u/Screenshot%202015-07-12%2016.50.51.png?dl=0

Scroll bars are also present on desktop:
https://www.dropbox.com/s/jtldnyhrr987tuv/Screenshot%202015-07-12%2016.52.16.png?dl=0

**Comment by jbaxleyiii** [comment]
@jonhorton this one plagues me. It also does it on perrynoble.com blog articles. Need to research more for solution

**Comment by jonhorton** [comment]
@jbaxleyiii I know what it is!

https://www.dropbox.com/s/xhwmbukuhsjz8d1/Screenshot%202015-07-12%2017.11.08.png?dl=0

My preferences have scrollbars set to Always show (I've never updated the default since newer version default to only when scrolling now). This works fine when I change the setting, but I'm sure there are other users with the setting set to Always.

I wonder if there's a way around it.

**Comment by jbaxleyiii** [comment]
@jonhorton I think there is a way with overflows to make the browser think there is nothing to scroll

**Comment by jbaxleyiii** [comment]
closed with https://github.com/NewSpring/apollos-core/pull/62
