### ISSUE TITLE
Hitting Enter within an input fields reloads the page and changes url

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#19]
**To reproduce**
Visit the /give page or a fund detail page.
Type 1.00 within the field
Hit Enter

**Buggy Behavior**
Page refreshes
URL is updated to http://45.55.213.136/give?tithe=%241.00
Not sure if the param is supposed to prefill the input, but it currently does not.

![Screen] (https://photos-5.dropbox.com/t/2/AADEu2STiyiXO0K1EsgO9que7czNf6UfmIrFB9fppw8I5A/12/9489940/png/32x32/1/1436742000/0/2/Screenshot%202015-07-12%2017.18.24.png/CJScwwQgASACIAcoASgCKAc/h0WXYXwU2Mae5SzOyHk97gjppdGYtoiFDwRlc0tfQYo?size=2048x1536&size_mode=2)

**Comment by jbaxleyiii** [comment]
Nice bug find! I'm thinking this should be an option to require valid data to submit. We will need to add that as a feature to https://github.com/NewSpring/apollos-core/blob/master/_source/client/templates/components/forms/form.coffee
