### ISSUE TITLE
Person record not updating

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/my.newspring.cc#20]

**Comment by jonhorton** [comment]
@jbaxleyiii While the person record isn't updating, it's appears to instead be creating new people every time: https://www.dropbox.com/s/bsc23eatsako9gm/Screenshot%202015-07-14%2021.31.55.png?dl=0

I have nearly 10 identical people on staging-rock from all the times I'm completed my profile!

**Comment by jbaxleyiii** [comment]
@jonhorton I just deployed a fix for this :+1: 

https://github.com/NewSpring/apollos-give/pull/55

**Comment by jbaxleyiii** [comment]
@jonhorton you may need to delete your user / person on staging-rock and create a new one to verify it
