### ISSUE TITLE
CSS bug on non-selected payment type button

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#22]
Button that isn't currently active is doesn't have rounded corners

Exhibit A: 
![image of jankiness](https://photos-4.dropbox.com/t/2/AAC0GWHryjcvZpLSVjnAQ6Z_5lU_AqcHFPNM23wnBv2cAw/12/9489940/png/32x32/1/1436803200/0/2/Screenshot%202015-07-12%2021.10.38.png/CJScwwQgASACIAcoASgCKAc/Q6XvsDpY6CksuV-opmaRT7oeZP0T-L9X8g57y8LEMXA?size=2048x1536&size_mode=2)

**Comment by jbaxleyiii** [comment]
@jonhorton can you take another screenshot ;)

**Comment by jonhorton** [comment]
@jbaxleyiii so strange—updated!

**Comment by jbaxleyiii** [comment]
@jonhorton I can't reproduce, what browser?

**Comment by jonhorton** [comment]
@jbaxleyiii well.....it appears to be fixed now! Good work!
