### ISSUE TITLE
Add wordmark to side panel/mobile header

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/my.newspring.cc#26]
Add wordmark to the sidepanel and mobile header.

https://www.dropbox.com/s/5kq261ru2c7k6ev/wordmark-white.svg?dl=0 

(https://cloud.githubusercontent.com/assets/7452283/8651008/8b0e6462-2944-11e5-9783-8a518a56e6d0.png)

**Comment by jbaxleyiii** [comment]
fixed in https://github.com/NewSpring/apollos-core/pull/61
