### ISSUE TITLE
overlays in modals on mobile are janky

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/my.newspring.cc#28]
![img](https://photos-5.dropbox.com/t/2/AABlhexDO7IyAcZapgppj9Ruu6VZUHMflaMY_dzq1zGDZA/12/376082959/png/32x32/1/1436803200/0/2/Screenshot%202015-07-13%2010.34.33.png/CI-kqrMBIAEgAiADIAQgBSAGIAcoASgCKAc/224IFGLjDNfsV733NkYCXcnw8LJd1IuLpEsLwtYzNCk?size=1280x960&size_mode=2)

**Comment by johnthepink** [comment]
@jbaxleyiii crap, that's the one i didn't look at. looking at it now
