### ISSUE TITLE
js console errors when clicking the Credit type button

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#29]
**To Reproduce**
- Give, to the point where you can choose bank/credit
- Click Credit button

Error appears every time credit is clicked: https://www.dropbox.com/s/n1c7rw5w9dbrpe2/Screenshot%202015-07-13%2014.54.23.png?dl=0

**Comment by jbaxleyiii** [comment]
@johnthepink @benwiley this looks like a duplication from trying to create a reactive var on the currency component

**Comment by jbaxleyiii** [comment]
```coffeescript
# maybe try this

  vars: -> 
    svg =  
      height: 40
      width: 54
      
  super.concat [
    cardType: null
    svgData: svg
  ]
```

**Comment by jbaxleyiii** [comment]
fixed with https://github.com/NewSpring/apollos-give/pull/47
