### ISSUE TITLE
Ensure that all image urls are protocol relative

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#30]
Error for insecure content: https://www.dropbox.com/s/8r4e0ivi3d8rauo/Screenshot%202015-07-13%2014.56.09.png?dl=0

For S3 to be protocol relative + SSL, the url format should be //s3.amazonaws.com/ns.images/your-additional-path-name/here.jpg

**Comment by jbaxleyiii** [comment]
should be fixed with https://github.com/NewSpring/apollos-give/pull/48
