### ISSUE TITLE
Receipt emails aren't being sent

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#32]
On successful contribution, emails aren't being sent.

https://www.dropbox.com/s/s021dnde70v58vw/Screenshot%202015-07-14%2010.12.37.png?dl=0

Suggest hooking this up to mailgun to mimic existing functionality!

**Comment by jbaxleyiii** [comment]
@jonhorton won't this be configured in Rock?

**Comment by jonhorton** [comment]
@jbaxleyiii hmm... good point. then we need to investigate why rock isn't sending them, if it's even configured, and also to make sure it actually can send receipts when a contribution is successful.

**Comment by jbaxleyiii** [comment]
Since this is with Rock I'm closing it. If we need to do it with Apollos we can use lookback:email package
