### ISSUE TITLE
Give now with one click language

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/my.newspring.cc#36]
Maybe we're working on this, but it feels a little wordy, and it looks strange on mobile.

https://www.dropbox.com/s/bfjv8yvwwjs1pv6/Screenshot%202015-07-14%2019.13.42.png?dl=0

**Comment by jbaxleyiii** [comment]
@jonhorton agreed on the wordiness. Thoughts on what is better? We need to convey that clicking will actually give just like on Amazon. Potential confusion comes from a give button normally requires more action

**Comment by richarddubay** [comment]
Do you have to say "with One Click"? What's wrong with just "Give Now"?

**Comment by samclaridge** [comment]
eet iss gown 2 b hupdayted 2 thees



https://www.dropbox.com/s/s2ulpg2oj0p2d1w/Screenshot%202015-07-15%2012.01.38.png?dl=0
