### ISSUE TITLE
All gifts are showing up in Rock as tithe

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/my.newspring.cc#41]
@benwiley thoughts on whats happening here?

**Comment by johnthepink** [comment]
@jbaxleyiii this is why

https://github.com/newspring/apollos-give/blob/master/_source/client/templates/cards/add-to-fund/states/add-to-fund.all.coffee#L361

We had hard coded it before we were pulling in accounts

**Comment by johnthepink** [comment]
We could fix this by publishing accounts to the client, or calling the server to get the account id. But, we probably need to figure out what our "Fund" to "Account" relationship is going to be moving forward.

**Comment by johnthepink** [comment]
Should be fixed by NewSpring/apollos-give#59
