### ISSUE TITLE
Back Breadcrumb

### ISSUE THREAD

**Issue by edolyne** [NewSpring/my.newspring.cc#42]
When navigating to a giving fund page, I would like to have a breadcrumb to take me back to the page I was on previously.

**Comment by jbaxleyiii** [comment]
@samclaridge thoughts on using the pattern established on giving receipts?

**Comment by samclaridge** [comment]
yessir, it was in the final artboards 


https://www.dropbox.com/s/e0kbtyvc13aiavh/Screenshot%202015-07-16%2016.40.05.png?dl=0

**Comment by johnthepink** [comment]
Will be fixed by NewSpring/apollos-give#62

**Comment by johnthepink** [comment]
Actually fixed in NewSpring/apollos-give#63
