### ISSUE TITLE
Funds with parenthesis don't work

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/my.newspring.cc#61]
Example: http://localhost:3000/give/#!/greenville-mission-(hurricane-sandy)

**Comment by jbaxleyiii** [comment]
@johnthepink we are encoding the URI for the route I thought

https://github.com/NewSpring/apollos-core/blob/master/_source/client/lib/components/component.coffee#L710

**Comment by johnthepink** [comment]
@jbaxleyiii it's this that is the problem:

https://github.com/newspring/apollos-give/blob/adjust-form-padding/_source/client/templates/cards/fund/states/fund.vision.coffee#L9-L12

**Comment by johnthepink** [comment]
@jbaxleyiii ^^ and that should fix it
