### ISSUE TITLE
Text feels too large on some phones

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/my.newspring.cc#76]
See my phone, (will upload image).

@samclaridge

**Comment by benwiley** [comment]
Can we quantify this somehow?  What text?  How much smaller should it be? Etc.

**Comment by jbaxleyiii** [comment]
@benwiley will do!

**Comment by jbaxleyiii** [comment]
![wp_ss_20150803_0001 1](https://cloud.githubusercontent.com/assets/4967600/9046003/a66b25f8-39f5-11e5-8f58-442ea6519299.jpg)
![wp_ss_20150803_0001](https://cloud.githubusercontent.com/assets/4967600/9045998/a662efaa-39f5-11e5-82bd-fec98db6e84e.jpg)
![wp_ss_20150803_0002](https://cloud.githubusercontent.com/assets/4967600/9046002/a665e944-39f5-11e5-9ed2-160f8e2a118f.jpg)
![wp_ss_20150803_0003](https://cloud.githubusercontent.com/assets/4967600/9045999/a6639c34-39f5-11e5-9cd4-53e75308b6ea.jpg)
![wp_ss_20150803_0004](https://cloud.githubusercontent.com/assets/4967600/9046000/a664a57a-39f5-11e5-8c59-6b297b060e84.jpg)
![wp_ss_20150803_0005](https://cloud.githubusercontent.com/assets/4967600/9046001/a664dcb6-39f5-11e5-9767-6dda4c2783b4.jpg)
![wp_ss_20150803_0006](https://cloud.githubusercontent.com/assets/4967600/9046004/a6706220-39f5-11e5-80a6-24b5e9336f70.jpg)

**Comment by johnthepink** [comment]
Here is the H3s reduced from 1.8em to 1.5em:

![wp_ss_20150804_0001](https://cloud.githubusercontent.com/assets/816517/9068471/b269264a-3ab1-11e5-977f-c14d8dd98bf6.jpg)

And here it is reduced to 1.25em:

![wp_ss_20150804_0002](https://cloud.githubusercontent.com/assets/816517/9068481/bc28df2c-3ab1-11e5-83ab-dcd070f3818c.jpg)
