### ISSUE TITLE
Keyboard won't close when covering input

### ISSUE THREAD

**Issue by benwiley** [NewSpring/my.newspring.cc#85]
Click on an input.  Scroll so that the "close keyboard" button is hovering over an input.  Click.  The keyboard fakes you out, making you think it's going to close, but then it doesn't.

<img src="http://i.perezhilton.com/wp-content/uploads/2014/03/blake-griffin-does-space-jam-table-read.gif" />

**Comment by johnthepink** [comment]
Closed by NewSpring/apollos-core#93
