### ISSUE TITLE
fund width

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/my.newspring.cc#87]
The fund card should be lap-wide so the fund card isn't so big on desktop

https://www.dropbox.com/s/dkue6a6viga1jf5/Screenshot%202015-07-29%2015.20.06.png?dl=0

instead of https://www.dropbox.com/s/27mg4yg2smbrh68/Screenshot%202015-07-29%2015.20.23.png?dl=0

@jbaxleyiii

**Comment by jbaxleyiii** [comment]
Change `desk-wide-and-up` to `lap-wide-and-up` here https://github.com/NewSpring/apollos-give/blob/master/_source/client/templates/pages/give.html#L30
