### ISSUE TITLE
On iPhone 4, the toggle indicator is fixed with scroll

### ISSUE THREAD

**Issue by benwiley** [NewSpring/my.newspring.cc#95]
The little arrow should stay placed immediately underneath "Bank" rather than follow me as I scroll.

![image](https://cloud.githubusercontent.com/assets/8700223/8967747/e5047b54-3606-11e5-9694-2b0b4e6efb9f.png)

**Comment by jbaxleyiii** [comment]
Duplicate of #74

**Comment by jbaxleyiii** [comment]
Needs `position: relative` on .toggle
